from .eb123 import I140_ANNUAL_APPROVALS, COUNTRY_APPROVALS
from .eb4 import (
    EB4_ANNUAL_TOTALS_BY_YEAR,
    SIJS_NATIONALITY_DISTRIBUTION,
    OTHER_EB4_NATIONALITY_DISTRIBUTION_BY_YEAR,
)
from .eb5 import (
    EB5_ANNUAL_TOTALS_BY_YEAR as EB5_HISTORICAL,
    EB5_NATIONALITY_DISTRIBUTION_BY_YEAR,
)
